services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-certi
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    container_name: api-certi
    depends_on:
      - mongodb
    build: 
      context: server
      dockerfile: ./dockerfile
    ports:
      - 9000:9000

  ui:
    image: ui
    container_name: ui-certi
    depends_on:
      - api
    build:
      context: ui
      dockerfile: ./dockerfile
    ports:
      - 3000:3000

volumes:
  mongo_volume: